version: '3.1'

services: 
    generator:
        build:
            context: .
        image: aspnetcore/generator:multi
        ports:
            - "8080:80"
    mail:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
            - "1025:1025" #remember to comment smtp port in production
